opa_server_url: "http://10.200.3.99:8181"
policies:
  fairness: "/v1/data/policies/fairness/demographic_parity/allow"
  reliability: "/v1/data/policies/reliability/allow"
  explainability: "/v1/data/policies/explainability/allow"
