# Use official Python image as base
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements_mlflow.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements_mlflow.txt

# Copy application code
COPY . .

# Command to run MLflow client and model aggregator if needed
# For this example, it's handled within the API server