# Use official Python image as base
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements_monitoring.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements_monitoring.txt

# Copy application code
COPY . .

# Expose metrics port
EXPOSE 8000

# Command to run the monitoring service
CMD ["python", "monitoring.py"]