apiVersion: v1
kind: Service
metadata:
  name: cloud-layer
  labels:
    app: cloud-layer
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 8080
    targetPort: 8080
    name: api-port
  selector:
    app: cloud-layer