apiVersion: v1
kind: Service
metadata:
  name: cloud-service
  labels:
    app: cloud-layer
spec:
  selector:
    app: cloud-layer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - name: prometheus
      port: 8000
      targetPort: 8000
  type: ClusterIP