apiVersion: v1
kind: Service
metadata:
  name: cloud-service
  labels:
    app: cloud
spec:
  selector:
    app: cloud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP