apiVersion: v1
kind: Service
metadata:
  name: edge-device-service
  labels:
    app: edge-device
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 8001
    targetPort: 8001
    name: edge-device-port
  selector:
    app: edge-device