apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 5002
    targetPort: 5002
    name: mlflow-port
  selector:
    app: mlflow