apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt-port
  selector:
    app: mosquitto