apiVersion: v1
kind: Service
metadata:
  name: opa-service
  namespace: default
  labels:
    app: opa
spec:
  selector:
    app: opa
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: ClusterIP