apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    app: opa
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 8181
    targetPort: 8181
    name: opa-port
  selector:
    app: opa