apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-server2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/data/edge-processing/server-2
  nodeAffinity:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - crest-bigdata-89acfcc4-c317-bf53-2acd-93bce3c87706-vm-2