apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: cloud-layer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
      - name: monitoring-service
        image: your-docker-registry/cloud_layer_monitoring:latest
        ports:
        - containerPort: 8000