apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: cloud-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: your-docker-registry/mlflow:latest
        ports:
        - containerPort: 5000
        command: ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "s3://your-bucket/mlflow/", "--host", "0.0.0.0", "--port", "5000"]
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-pvc