apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: cloud-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: cloud-layer
data:
  mosquitto.conf: |
    pid_file /var/run/mosquitto/mosquitto.pid
    listener 1883
    allow_anonymous true
    # WebSocket listener (optional)
    listener 9001
    protocol websockets