apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-server'
        static_configs:
          - targets: ['api-server-service.cloud-layer.svc.cluster.local:8000']
      - job_name: 'edge-processing'
        static_configs:
          - targets: ['edge-processing-service.cloud-layer.svc.cluster.local:5000']
      - job_name: 'mlflow-server'
        static_configs:
          - targets: ['mlflow-service.cloud-layer.svc.cluster.local:5000']
      - job_name: 'mqtt-broker'
        static_configs:
          - targets: ['mqtt-broker-service.cloud-layer.svc.cluster.local:1883']