apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: cloud-layer
spec:
  selector:
    app: monitoring-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP