apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: cloud-layer
spec:
  selector:
    app: mlflow-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer