apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: cloud-layer
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer