apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-fairness-policies
  namespace: default
data:
  fairness_thresholds.json: |
    {
      "fairness": {
        "threshold": {
          "accuracy": 0.4,
          "demographic_parity_difference": 0.05
        }
      }
    }
  demographic_parity.rego: |
    package policies.fairness.demographic_parity

    default allow = false

    allow {
        input.fairness.metrics.demographic_parity_difference <= input.fairness.threshold.demographic_parity_difference
        input.fairness.metrics.accuracy >= input.fairness.threshold.accuracy
    }