apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-explainability-policies
  namespace: default
data:
  explainability_thresholds.json: |
    {
      "explainability": {
        "threshold": {
          "explainability_score": 0.6
        }
      }
    }
  explainability.rego: |
    package policies.explainability

    # default allow = false

    allow {
      input.explainability_score >= input.thresholds.explainability_score
    }