apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-reliability-policies
  namespace: default
data:
  reliability_thresholds.json: |
    {
      "reliability": {
        "threshold": {
          "reliability_score": 0.8
        }
      }
    }
  reliability.rego: |
    package policies.reliability

    # default allow = false

    allow {
        input.reliability_score >= input.threshold.reliability_score
    }