apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-fairness-policies
  namespace: default
data:
  fairness_thresholds.json: |
    {
      "fairness": {
        "threshold": {
          "demographic_parity_difference": 0.05
        }
      }
    }
  fairness.rego: |
    package policies.fairness

    # default allow = false

    allow if {
        input.fairness.metrics.demographic_parity_difference <= input.fairness.threshold.demographic_parity_difference
    }