apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config-writable
          mountPath: /mosquitto/config
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
      initContainers:
      - name: init-mosquitto-config
        image: busybox
        command: ['sh', '-c', 'cp /mosquitto-config-readonly/mosquitto.conf /mosquitto-config-writable/mosquitto.conf']
        volumeMounts:
        - name: mosquitto-config-readonly
          mountPath: /mosquitto-config-readonly
        - name: mosquitto-config-writable
          mountPath: /mosquitto-config-writable
      volumes:
      - name: mosquitto-config-readonly
        configMap:
          name: mosquitto-config
      - name: mosquitto-config-writable
        emptyDir: {}
      - name: mosquitto-data
        emptyDir: {}
      - name: mosquitto-log
        emptyDir: {}