apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /mosquitto/config && cp /config/mosquitto.conf /mosquitto/config/mosquitto.conf && addgroup -S mosquitto && adduser -S mosquitto -G mosquitto && chown mosquitto:mosquitto /mosquitto/config/mosquitto.conf']
          volumeMounts:
            - name: mosquitto-config
              mountPath: /config
            - name: mosquitto-config-writable
              mountPath: /mosquitto/config
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config-writable
              mountPath: /mosquitto/config
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-log
              mountPath: /mosquitto/log
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-config-writable
          emptyDir: {}
        - name: mosquitto-data
          emptyDir: {}
        - name: mosquitto-log
          emptyDir: {}