apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: default
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      imagePullSecrets:
        - name: mlops
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--set=decision_logs.console=true"
            - "--set=decision_logs.format=json"
            - "--watch"
            - "/policies"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: fairness-policies
              mountPath: /policies/fairness
            - name: reliability-policies
              mountPath: /policies/reliability
            - name: explainability-policies
              mountPath: /policies/explainability
      volumes:
        - name: fairness-policies
          configMap:
            name: opa-fairness-policies
            items:
              - key: fairness_thresholds.json
                path: fairness_thresholds.json
              - key: demographic_parity.rego
                path: demographic_parity.rego
        - name: reliability-policies
          configMap:
            name: opa-reliability-policies
            items:
              - key: reliability_thresholds.json
                path: reliability_thresholds.json
              - key: reliability.rego
                path: reliability.rego
        - name: explainability-policies
          configMap:
            name: opa-explainability-policies
            items:
              - key: explainability_thresholds.json
                path: explainability_thresholds.json
              - key: explainability.rego
                path: explainability.rego