apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-processing-deployment
  labels:
    app: edge-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-processing
  template:
    metadata:
      labels:
        app: edge-processing
    spec:
      imagePullSecrets:
        - name: mlops
      containers:
      - name: edge-processing
        image: edgemlops/edge-processing-server:latest
        ports:
        - containerPort: 8000
        - containerPort: 5002  # MLflow server
        - containerPort: 8181  # OPA server
        env:
          - name: MQTT_BROKER
            value: "mosquitto-service"
          - name: MQTT_PORT
            value: "1883"
          - name: MQTT_TOPIC_UPLOAD
            value: "models/upload"
          - name: MQTT_TOPIC_AGGREGATED
            value: "models/aggregated"
          - name: EXPECTED_DEVICES
            value: "2"
          - name: CLOUD_API_URL
            value: "http://cloud-layer-service:8080"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: "Exists"