apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: edge-processing-server-1
  labels:
    app: edge-processing
    server: server-1
spec:
  serviceName: "edge-processing-server-1"
  replicas: 1
  selector:
    matchLabels:
      app: edge-processing
      server: server-1
  template:
    metadata:
      labels:
        app: edge-processing
        server: server-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - crest-bigdata-89acfcc4-c317-bf53-2acd-93bce3c87706-vm-1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - edge-processing
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edge-processing
        image: edgemlops/edge-processing-server:latest
        ports:
        - containerPort: 8000
        - containerPort: 5002  # MLflow server
        - containerPort: 8181  # OPA server
        - containerPort: 1883  # MQTT broker
        env:
          - name: MQTT_BROKER
            value: "10.42.1.104" #"10.42.1.12"
          - name: MQTT_PORT
            value: "1883"
          - name: MQTT_TOPIC_UPLOAD
            value: "models/upload"
          - name: MQTT_TOPIC_AGGREGATED
            value: "models/aggregated"
          - name: EXPECTED_DEVICES
            value: "2"
          - name: EDGE_SERVER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CLOUD_API_URL
            value: "http://cloud-layer:8080"
          - name: MLFLOW_TRACKING_URI
            value: "http://10.42.1.53:5002" #"http://mlflow:5002"
          - name: USE_MLFLOW
            value: "false"
          - name: PYTHONPATH
            value: "/app"
          - name: PYTHONUNBUFFERED
            value: "1"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"