apiVersion: v1
kind: Service
metadata:
  name: edge-processing-service
  labels:
    app: edge-processing
spec:
  selector:
    app: edge-processing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 5002
      targetPort: 5002
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: ClusterIP