apiVersion: v1
kind: Service
metadata:
  name: edge-device-service
  labels:
    app: edge-device
spec:
  selector:
    app: edge-device
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP