apiVersion: v1
kind: Service
metadata:
  name: edge-processing-service
  labels:
    app: edge-processing
spec:
  selector:
    app: edge-processing
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: mlflow
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: opa
      protocol: TCP
      port: 8181
      targetPort: 8181
  type: ClusterIP